DROP TABLE ref_hcg;
CREATE EXTERNAL TABLE IF NOT EXISTS ref_hcg (
  MR_LINE_CASE_KEY VARCHAR (4),
  CODE_SET_YEAR VARCHAR (4),
  MR_LINE_DESC2 VARCHAR (50),
  MR_LINE VARCHAR (4), 
  MR_LINE_DESC VARCHAR (50), 
  PROD_TYPE VARCHAR (20),
  MR_LINE_DESC1 VARCHAR (4), 
  HCG_DESC_02 VARCHAR (20)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
LOCATION 's3://com.samstearns.nh/files/REF_HCG.txt';


CREATE EXTERNAL TABLE IF NOT EXISTS mc (
  COVERAGE_CLASS VARCHAR (3),
  FROM_YEAR VARCHAR (4), 
  ADM_YR INT, 
  DIS_YR INT, 
  CLAIM_ID_KEY INT,   
  CS_CLAIM_ID_KEY INT, 
  SERVICES_KEY INT, 
  SV_LINE NUMBER INT, 
  FORM_TYPE VARCHAR (1),   
  SV_STAT VARCHAR (1), 
  DIS_STAT NUMBER INT, 
  POS VARCHAR (2), 
  AGE VARCHAR (3),   
  SEX VARCHAR (2), 
  MEMBER_COUNTY INT, 
  MEMBER_STATE VARCHAR (2), 
  PRODUCT_TYPE VARCHAR (3),   
  LOB VARCHAR (10), 
  INSURANCE_TYPE VARCHAR (2), 
  PROC_CODE VARCHAR (10), 
  CPT_MOD1 VARCHAR (2),   
  CPT_MOD2 VARCHAR (2), 
  REV_CODE VARCHAR (10), 
  UB_BILL_TYPE VARCHAR (3), 
  ADM_SRC VARCHAR (2),   
  ADM_TYPE INT, 
  CLIENT_LOS INT, 
  ICD_10_OR_HIGHER INTEGER, 
  ICD_PROC_01_PRI VARCHAR (7),   
  ICD_DIAG_01_PRIMARY VARCHAR (7), 
  ICD_DIAG_ADMIT VARCHAR (7), 
  ICD_DIAG_02 VARCHAR (7), 
  ICD_DIAG_03 VARCHAR (7), 
  ICD_DIAG_04 VARCHAR (7), 
  ICD_DIAG_05 VARCHAR (7), 
  ICD_DIAG_06 VARCHAR (7), 
  ICD_DIAG_07 VARCHAR (7), 
  ICD_DIAG_08 VARCHAR (7), 
  ICD_DIAG_09 VARCHAR (7), 
  ICD_DIAG_10 VARCHAR (7), 
  ICD_DIAG_11 VARCHAR (7), 
  ICD_DIAG_12 VARCHAR (7), 
  ICD_DIAG_13 VARCHAR (7),
  SERV_PROV_CW_KEY INT,
  BILL_PROV_CW_KEY INT,
  QTY INT, 
  AMT_BILLED INT, 
  AMT_PAID INT, 
  AMT_DEDUCT INT, 
  AMT_COINS INT, 
  AMT_COPAY INT, 
  AMT_PREPAID INT, 
  INPATIENT_FLAG VARCHAR (1), 
  MR_LINE_CASE_KEY VARCHAR (4), 
  CASES INT, 
  UTILS INT, 
  NDC VARCHAR (11), 
  CLAIM_STATUS_ORIG VARCHAR (2), 
  ECODE_ORIG VARCHAR (10), 
  ADMIT_HOUR VARCHAR (4), 
  DISCHARGE_HOUR VARCHAR (4), 
  CLAIM_ADJUSTMENT_LOGIC VARCHAR (4), 
  IMPUTED_SERVICE_KEY VARCHAR (50)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
LOCATION 's3://com.samstearns.nh/2019/2019.txt';
