CREATE DATABASE NH_APCD COMMENT = 'NH Database';

DROP TABLE IF EXISTS REF_FORM_TYPE;
CREATE TABLE REF_FORM_TYPE (
  FORM_TYPE VARCHAR (1), 
  FORM_TYPE_DESC VARCHAR (100)
);

DROP TABLE IF EXISTS REF_HCG;
CREATE TABLE REF_HCG (
  MR_LINE_CASE_KEY VARCHAR (4), 
  CODE_SET_YEAR VARCHAR (4), 
  MR_LINE_DESC2 VARCHAR (50), 
  MR_LINE VARCHAR (4), 
  MR_LINE_DESC VARCHAR (100), 
  PROD_TYPE VARCHAR (20),
  MR_LINE_DESC1 VARCHAR (4), 
  HCG_DESC_02 VARCHAR (20)
);

DROP TABLE IF EXISTS CLAIM_MC;                                                                                                    
CREATE TABLE CLAIM_MC (
  COVERAGE_CLASS VARCHAR (3),
  FROM_YEAR VARCHAR (4), 
  ADM_YR NUMERIC (4,0), 
  DIS_YR NUMERIC (4,0), 
  CLAIM_ID_KEY NUMERIC (12,0),   
  CS_CLAIM_ID_KEY NUMERIC (12,0), 
  SERVICES_KEY NUMERIC (22,0), 
  SV_LINE NUMERIC (6,0), 
  FORM_TYPE VARCHAR (1),   
  SV_STAT VARCHAR (1), 
  DIS_STAT NUMERIC (2,0), 
  POS VARCHAR (2), 
  AGE VARCHAR (3),   
  SEX VARCHAR (2), 
  MEMBER_COUNTY NUMERIC (5,0), 
  MEMBER_STATE VARCHAR (2), 
  PRODUCT_TYPE VARCHAR (3),   
  LOB VARCHAR (10), 
  INSURANCE_TYPE VARCHAR (2), 
  PROC_CODE VARCHAR (10), 
  CPT_MOD1 VARCHAR (2),   
  CPT_MOD2 VARCHAR (2), 
  REV_CODE VARCHAR (10), 
  UB_BILL_TYPE VARCHAR (3), 
  ADM_SRC VARCHAR (2),   
  ADM_TYPE NUMERIC (2,0), 
  CLIENT_LOS NUMERIC (4,0), 
  ICD_10_OR_HIGHER INTEGER, 
  ICD_PROC_01_PRI VARCHAR (7),   
  ICD_DIAG_01_PRIMARY VARCHAR (7), 
  ICD_DIAG_ADMIT VARCHAR (7), 
  ICD_DIAG_02 VARCHAR (7), 
  ICD_DIAG_03 VARCHAR (7), 
  ICD_DIAG_04 VARCHAR (7), 
  ICD_DIAG_05 VARCHAR (7), 
  ICD_DIAG_06 VARCHAR (7), 
  ICD_DIAG_07 VARCHAR (7), 
  ICD_DIAG_08 VARCHAR (7), 
  ICD_DIAG_09 VARCHAR (7), 
  ICD_DIAG_10 VARCHAR (7), 
  ICD_DIAG_11 VARCHAR (7), 
  ICD_DIAG_12 VARCHAR (7), 
  ICD_DIAG_13 VARCHAR (7),
  SERV_PROV_CW_KEY NUMERIC (12,0),
  BILL_PROV_CW_KEY NUMERIC (12,0),
  QTY NUMERIC (5,0), 
  AMT_BILLED NUMERIC (10,2), 
  AMT_PAID NUMERIC (10,2), 
  AMT_DEDUCT NUMERIC (10,2), 
  AMT_COINS NUMERIC (10,2), 
  AMT_COPAY NUMERIC (10,2), 
  AMT_PREPAID NUMERIC (10,2), 
  INPATIENT_FLAG VARCHAR (1), 
  MR_LINE_CASE_KEY VARCHAR (4), 
  CASES NUMERIC (6,0), 
  UTILS NUMERIC (5,0), 
  NDC VARCHAR (11), 
  CLAIM_STATUS_ORIG VARCHAR (2), 
  ECODE_ORIG VARCHAR (10), 
  ADMIT_HOUR VARCHAR (4), 
  DISCHARGE_HOUR VARCHAR (4), 
  CLAIM_ADJUSTMENT_LOGIC VARCHAR (4), 
  IMPUTED_SERVICE_KEY VARCHAR (50)
);

DROP TABLE IF EXISTS "NH_APCD"."public"."REF_PROVIDER";
CREATE TABLE public."REF_PROVIDER" (
  "PROV_KEY" NUMERIC (12), 
  "PROV_CW_KEY" NUMERIC (20),
  "FACILITY_ NAME" VARCHAR(255),
  "PROV_TYPE" VARCHAR (20),
  "PROV_TYPE_ORIG" VARCHAR (2),
  "PROV_CLINIC_ STATE" VARCHAR (2),
  "NH_COUNTY_CODE" NUMERIC (5)          
);
